// Regenerates ../src/admin/dashboardHtml.ts from dist/index.html after a build.
// Run via `npm run build` in this directory (already wired to call this).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, "dist/index.html"), "utf8");
const outPath = join(__dirname, "../src/admin/dashboardHtml.ts");

const out = `/**
 * The admin dashboard, pre-built and embedded as a plain string constant.
 *
 * Why embedded instead of served as a static file: this project's
 * vercel.json rewrites EVERY path to the one serverless function (needed
 * for /mcp, /authorize, /token, etc. to all work through a single
 * function). That means Vercel's normal static-file serving from public/
 * never gets a chance to run for /admin's assets, and a Vercel Node
 * function's filesystem at runtime isn't guaranteed to include files
 * outside its traced import graph anyway. Embedding the built HTML as a
 * string sidesteps that whole class of problem.
 *
 * DO NOT EDIT THIS FILE DIRECTLY. Edit the source in admin/src/, then:
 *   cd admin && npm install && npm run build
 * This regenerates this exact file automatically (see admin/embed.mjs).
 *
 * Built with vite-plugin-singlefile — one self-contained HTML file with all
 * JS and CSS inlined, no separate asset requests at all.
 */

export const ADMIN_DASHBOARD_HTML = ${JSON.stringify(html)};
`;

writeFileSync(outPath, out, "utf8");
console.log(`Wrote ${outPath} (${out.length.toLocaleString()} bytes)`);
